### ISSUE TITLE
fs.wrapper() custom pipeline errors

### ISSUE THREAD

**Issue by tdhooghe** [CaroFuchs/pyFUME#2]
Dear Caro,

I am running into some errors when I try to run the wrapper to a custom pipeline.

This is the code I am trying to run:
```
path_data = './Previous_house_sales.csv'
house_data = pd.read_csv(path_data)  # create a dataframe of the data
var_names = list(house_data.columns)[0:11]  # don't get the name of the target variable 

# load the dataframe in the data loader class
dl = DataLoader(dataframe=house_data, normalize='minmax', verbose=True)
fs_wrap = FeatureSelector(dl.dataX, dl.dataY, nr_clus=2, variable_names=var_names)
x, y, z = fs_wrap.wrapper()
```
And this is the error I receive

```
Traceback (most recent call last):
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-13-bfa0dae3a1ad>", line 5, in <module>
    x, y, z = fs_wrap.wrapper()
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/pyfume/FeatureSelection.py", line 92, in wrapper
    selected_feature_names = self.variable_names[selected_features]
TypeError: list indices must be integers or slices, not list
```

Running the following line
`Fuzzy_model = pyFUME(dataframe=house_data, feature_selection='wrapper')`
raises this traceback
```
Traceback (most recent call last):
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-c68fdf95e062>", line 3, in <module>
    Fuzzy_model = pyFUME(dataframe=house_data, feature_selection='wrapper')
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/pyfume/pyfume.py", line 51, in __init__
    self.FIS = BuildTSFIS(dataframe=dataframe, nr_clus=self.nr_clus, variable_names=variable_names, process_categorical=process_categorical, merge_threshold=merge_threshold, **kwargs)
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/pyfume/BuildTakagiSugeno.py", line 125, in __init__
    self.selected_feature_indices, self.variable_names=fs.wrapper()
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/pyfume/FeatureSelection.py", line 92, in wrapper
    selected_feature_names = self.variable_names[selected_features]
TypeError: list indices must be integers or slices, not list
```
but the following does not give any error, hence it looked like it is a problem with the dataframe.

`Fuzzy_model = pyFUME(datapath=path_data, feature_selection='wrapper')`

Then I tried the following hoping this would solve the error,
```
dl = DataLoader(**datapath=path_data**, normalize='minmax', verbose=True)
fs_wrap = FeatureSelector(dl.dataX, dl.dataY, nr_clus=2, variable_names=var_names)
x, y, z = fs_wrap.wrapper()
```
but this also resulted in about the same error, seeming like it has nothing to do with the dataframe after all.
```
Traceback (most recent call last):
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-f56a1d73a17c>", line 5, in <module>
    x, y, z = fs_wrap.wrapper()
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/pyfume/FeatureSelection.py", line 92, in wrapper
    selected_feature_names = self.variable_names[selected_features]
TypeError: list indices must be integers or slices, not list
```

I hope we can figure this out :) 

Kind regards,
Thomas

**Comment by CaroFuchs** [comment]
Dear Thomas,

Thank you for pointing out this issue! It should be resolved in the newest release of pyFUME. Please pip upgrade to the newest version (v 0.1.26) and try running your code again!

Kind regards,

Caro

**Comment by tdhooghe** [comment]
No problem at all, thank you for your quick response! 
Running the following now successfully completes
`Fuzzy_model = pyFUME(dataframe=house_data, feature_selection='wrapper')`

However, the following code
```
dl = DataLoader(dataframe=house_data, normalize='minmax', verbose=True)
fs_wrap = FeatureSelector(dl.dataX, dl.dataY, nr_clus=2, variable_names=var_names)
x, y, z = fs_wrap.wrapper()
```
now raises the following traiseback
```
Traceback (most recent call last):
  File "/home/thomas/Documents/1BM120_computational_intelligence/py39env/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-bfa0dae3a1ad>", line 5, in <module>
    x, y, z = fs_wrap.wrapper()
ValueError: not enough values to unpack (expected 3, got 2)
```

Hopefully this is useful for you as well!

**Comment by tdhooghe** [comment]
Thank you for your amazingly quick fix, works like a charm!
